### ISSUE TITLE
WG meetup before/after GraphQL Summit 

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-wg#102]
Currently, WG scheduled for `2018-11-08` and that conflicts with 2nd day of GraphQL Summit:
https://github.com/graphql/graphql-wg/blob/master/agendas/2018-11-08.md
https://summit.graphql.com/
Would be great to move WG to either November 6th or 9th?

@leebyron Do you plan to organize special WG session similar to graphql-europe?
If so would be great to decide on the date so participants are able to buy plane tickets while they still cheap.

**Comment by leebyron** [comment]
Great point. I'll move it to the 6th and we can look into holding a special in-person sessions
