### ISSUE TITLE
[2022-07-07] EVERYONE: take a look at the GraphQL-over-HTTP spec

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1056]
We recently re-worked the spec with a focus on backwards compatibility and the introduction of a "watershed" for the `application/graphql+json` media type - after 1st Jan 2025 all GraphQL servers MUST support this media encoding to enable clients to determine whether or not responses using 4xx and 5xx status codes are from a GraphQL service.

We're working on final edits with a hope of getting this into the October spec cut (as a separate specification), so please review the spec here: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md

(Ideally wait a week for some more minor edits to land, but any time you can spend would be appreciated!)

This segment started in the video here: https://youtu.be/gVCszBu_aJI?t=6097

- assignee(s): everyone (champion: @ghmcadams / @benjie)
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-07-07.md#small-update-on-the-graphql-over-http-working-group-10m-benjie

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Denis making a lot of progress, input from many sources incl Apollo - successfully got eyes on
