### ISSUE TITLE
[2022-07-07] Open a discussion thread for struct

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1058]
Unfortunately we did not have enough time to discuss the struct RFC #1035; so we should open a discussion thread for it.

> Benjie: just a heads up, struct might be a replacement for oneOf, so if you’re using that… :man_shrugging: 
> ACTION - Benjie - open discussion thread for struct

Action assigned here: https://youtu.be/gVCszBu_aJI?t=8079

- assignee(s): @benjie
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-07-07.md#deferstream-20m-rob-richard:~:text=ACTION%20%2D%20Benjie%20%2D%20open%20discussion%20thread%20for%20struct

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by mattste** [comment]
I just read through the RFC and have an example use-case where this would have helped greatly. I can't seem to find a discussion thread so going to leave this here for now.

Recently, I was working on a feature where we had a schema like this:
```
type Script {
  commands: Command!
}

union Command = WatchCommand | PracticeCommand

input ScriptInput {
  commands: [CommandInput!]!
}

type CommandInput @oneOf {
    watchCommand: WatchCommandInput!
    practiceCommand: PracticeCommandInput!
}
```

In reality, we had about 10 different command types, each of which was relatively large with its fields.

A `Script` fetch or update was all-or-nothing. We store it in a JSON field in the database. We still wanted GraphQL's great type system for consumers and updaters to know what is expected (and code gen) but do not plan on doing fine-grained resolvers or mutations. It was extremely verbose to model both input/output for this use case.

**Comment by benjie** [comment]
Discussion thread raised: https://github.com/graphql/graphql-wg/discussions/1071

Do you fancy copying your comment accross @mattste? It's a great use case of struct!

**Comment by mattste** [comment]
> Discussion thread raised: #1071
> 
> Do you fancy copying your comment accross @mattste? It's a great use case of struct!

Done! Thanks!
