### ISSUE TITLE
[2022-08-04] Poll people on what they feel the domain of the spec is

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1099]
> Action - goal: seems you've done an inwards-out approach that you're getting pushback from, maybe you should try an outside-in approach where you try and pull from people what they feel the domain of the spec is. It seems most of the WG has a shared opinion on what that is.

[:movie_camera:  Timestamped YouTube link](https://youtu.be/eTlYuy8W_LU?t=6625)

- assignee(s): @rivantsov 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-08-04.md#:~:text=Action%20%2D%20goal%3A%20seems%20you%27ve%20done%20an%20inwards%2Dout%20approach%20that%20you%27re%20getting%20pushback%20from%2C%20maybe%20you%20should%20try%20an%20output%2Din%20approach%20where%20you%20try%20and%20pull%20from%20people%20what%20they%20feel%20the%20domain%20of%20the%20spec%20is.%20It%20seems%20most%20of%20the%20WG%20has%20a%20shared%20opinion%20on%20what%20that%20is.

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by rivantsov** [comment]
Sorry for no action here for 2 weeks, been bit busy. 

I would kindly ask to carry over this action item to the next month - I need more time to figure out the 'action', the poll question and extra arguments. 

The problem I see it is that the suggested poll question - 'what the domain spec IS now' - is a bit off target. I myself, being asked this question, would give an answer that I would immediately oppose when it would come to 'what it should be vs what it is'. When it comes to what it should be (the domain and scope), I think before doing a poll, I would need more and better arguments and examples, showing that with current situation (absence of clear definition statement), there are inherent problems - like things that do not seem very logical to new-comers, or implicit contextual knowledge brought in by practitioners but not explicitly stated - making things confusing.
 
So again, asking for an extra time. 
thank you.

**Comment by benjie** [comment]
There’s no rush @rivantsov! We’ve got action items open from over a year ago, people address them as and when they have time. Just update us when it’s ready to be reviewed and we’ll add it to the queue for the next meeting at that time.

**Comment by benjie** [comment]
As [agreed at the October 2023 WG](https://github.com/graphql/graphql-wg/blob/main/notes/2023/2023-10.md#review-previous-meetings-action-items-5m-lee); action items that have been inactive for more than 6 months can be closed. If you feel this issue is still requires more input, please comment below.
