### ISSUE TITLE
Clarify Zoom link for first APAC WG meeting (Oct 2022)

### ISSUE THREAD

**Issue by dondonz** [graphql/graphql-wg#1130]
Hello,

For the first APAC WG meeting coming up, the agenda has a different Zoom link to the calendar invite https://github.com/graphql/graphql-wg/blob/main/agendas/2022/10-Oct/wg-secondary-apac.md

Which is the correct link?

Agenda has
```
Video Conference Link: https://zoom.us/j/593263740
Password: graphqlwg
```

Google Calendar invite has
```
Join Zoom Meeting
https://zoom.us/j/92300060973
(no password provided)
```

Thanks.

**Comment by benjie** [comment]
Hi @dondonz, thanks for the heads up on this! I've raised it with the relevant parties but the general rule is trust what's in the agenda rather than what's in the calendar - it's always a good idea to check the agenda a couple days before the meeting.

**Comment by dondonz** [comment]
Thanks @benjie
