### ISSUE TITLE
🗳 2023 Technical Steering Committee (TSC) Elections 🗳

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#1175]
I hope you're not tired of elections, because it's time to run our own.

Please see the [2022 TSC Elections process](https://github.com/graphql/graphql-wg/issues/765) for context from last year.

While our charter calls for Elections concluding by the end of the year, since we're opening nominations late, we'll shift the elections schedule by one month to allow for more time for nominations (and extend existing terms by the same).

---

The GraphQL technical project is governed by our [technical steering committee (TSC)](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md).

The TSC was initially seeded in Nov 2020 with ten individuals plus the exec director (myself). Elections are held for five seats per year with each elected member to serve a 2 year term.

### TSC election process overview:

Please read the complete [rules for this elections process](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#becoming-a-tsc-voting-member). However here is a brief overview:

1. Five TSC members end their terms on Jan 31st (this year delayed by one month, see above).
2. Between now and then we [collect nominations](https://tsc-nomination.graphql.org/) and elect five members for these seats.
3. Existing TSC members may (but are not required to) nominate themselves for an additional term.
4. The TSC members not up for election (remaining 5 plus myself) vote on nominees using the [Condorcet method](https://en.wikipedia.org/wiki/Condorcet_method).

### Upcoming dates:

|                  |       |
|  --------- | --- |
| **Nov 16** | Nominations open. If interested, please submit your name with [this form](https://tsc-nomination.graphql.org/).
| **Dec 31** | Nominations close.
| **Jan 1** | Voting by remaining TSC to begin.
| **Jan 31** | Voting ends and new TSC members announced (or earlier!).
| **Jan 31** | Prior TSC members' term ends.
| **Feb 1, 2022** | New TSC members' two-year term begins. (Note: The next TSC/WG meeting to be held Feb 2nd, 2022)
| **Dec 31, 2023** | New TSC members' two-year term ends.

### Expiring TSC member terms:

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Andi Marek](https://github.com/andimarek)         | GraphQL Java          | Nov 1, 2020 | Jan 31, 2023 |
| [Dan Schafer](https://github.com/dschafer)         | Facebook              | Nov 1, 2020 | Jan 31, 2023 |
| [Nick Schrock](https://github.com/schrockn)        | Elementl              | Nov 1, 2020 | Jan 31, 2023 |
| [Rob Zhu](https://github.com/robzhu)               | AWS                   | Nov 1, 2020 | Jan 31, 2023 |
| [Sasha Solomon](https://github.com/sachee)         | Twitter               | Nov 1, 2020 | Jan 31, 2023 |

### Members voting in this election:

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Lee Byron (chair)](https://github.com/leebyron)   | GraphQL Specification | N/A         | N/A          |
| [Benjie Gillam](https://github.com/benjie)         | Graphile              | Nov 1, 2020 | Dec 31, 2023 |
| [Ivan Goncharov](https://github.com/IvanGoncharov) | Apollo                | Nov 1, 2020 | Dec 31, 2023 |
| [Marc-Andre Giroux](https://github.com/xuorig)     | Netflix               | Jan 1, 2022 | Dec 31, 2023 |
| [Matt Mahoney](https://github.com/mjmahone)        | Facebook              | Nov 1, 2020 | Dec 31, 2023 |
| [Michael Staib](https://github.com/michaelstaib)   | ChilliCream           | Jan 1, 2022 | Dec 31, 2023 |

### TSC responsibilities overview:

Please read the complete [TSC scope](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#scope). However here is a brief overview of expectations:

* At a minimum, TSC members are responsible for guiding the GraphQL project via voting on approving proposals and spec releases.
* TSC members are encouraged to participate in working group meetings and help maintain technical progress, process and procedure.
* TSC members are administrators of Github and other technical spaces, and may be asked to help resolve problems.
* TSC members serve for two years, but may abandon their seat early via special election.

_Note: Working group meetings remain open to all who wish to join and contribute. The RFC process by which GraphQL evolves uses a consensus model, and TSC rarely intervene with this model. Our goal remains to maintain open contribution._

### Important links:

* [Self-nomination form](https://tsc-nomination.graphql.org/)
* [TSC information and rules](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md)
* [GraphQL technical charter](https://github.com/graphql/foundation/blob/master/GraphQL%20Specification%20Membership%20Agreement%20February%202019.pdf)

I'm happy to answer any questions within this issue!

**Comment by leebyron** [comment]
cc @graphql/tsc

**Comment by dschafer** [comment]
My term is expiring this year, and since my day-to-day work hasn't involved GraphQL as of late, I'm not planning on renominating myself so that my seat can open up for a new TSC member. The community and the TSC are clearly in good hands, and I'm excited to see how GraphQL continues to grow and evolve in the years ahead!

**Comment by robzhu** [comment]
I will not be renominating myself so that someone else can have a chance to work with this amazing group and drive the GraphQL  ecosystem forward. However, I plan on staying an active member of the working group.

**Comment by schrockn** [comment]
Similarly I will not be renominating myself. Second Dan's sentiment that this is clearly in good hands and it's exciting to see the GraphQL continue to grow, expand, and mature!

**Comment by leebyron** [comment]
Thank you to everyone who nominated themselves for a TSC role, and for our now emeritus TSC members for creating space for a host of new members.

We had ten excellent nominees, and last week the remaining TSC members voted by way of preference ordering (using [Meek STV](https://blog.opavote.com/2017/04/meek-stv-explained.html))

Next elected members are (in alpha order)...

🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁 🥁

Andi Marek @andimarek 
Kewei Qu @Keweiqu 
Rob Richard @robrichard 
Stephen Spalding @fotoetienne 
Uri Goldshtein @Urigo 

👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

Huge congratulations to this group, and thank you for helping us keep the GraphQL project organized and effective!
