### ISSUE TITLE
Legal sign-off for GraphQL Scalars project

### ISSUE THREAD

**Issue by dondonz** [graphql/graphql-wg#1206]
Finalising legal sign-off for GraphQL Scalars project.

Would it be possible to re-use the same license used for other GraphQL Foundation projects such as the spec? 

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/main/agendas/2022/12-Dec/wg-secondary-apac.md

PR with GraphQL Foundation MIT License: https://github.com/graphql/graphql-scalars/pull/16/files

cc @benjie

**Comment by leebyron** [comment]
This is now done. We have all correct legal and copyright references in place

**Comment by dondonz** [comment]
Thanks @leebyron!!
