### ISSUE TITLE
[2022-11] if a field is deprecated on a type, it must be deprecated on the interface

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1331]
Does this rule already exist? Should it?

> Matt: do we have the rule that if a field is deprecated on a type then it must also be deprecated on any interface?
> Lee: good question
> Ivan: no, we don't have this rule.
> Stephen: sounds like another PR; it probably should - right?
> Lee: yeah, it's surprising that hasn't come up in the Facebook API.
> Matt: interface fields tend to be Hack/PHP; everyone gets the same implementation (same code executed) - deprecating it deprecates it everywhere.
> ACTION - validate this.

- assignee(s): unknown
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-11.md#deprecated-on-object-15m-stephen

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
Finally catching up with filing action items...

@mjmahone @fotoetienne Would either of you like to take this on?

**Comment by benjie** [comment]
GraphQL.js PR raised here: https://github.com/graphql/graphql-js/pull/3986

**Comment by benjie** [comment]
Added to next WG: https://github.com/graphql/graphql-wg/pull/1429

**Comment by fotoetienne** [comment]
Amazing, thanks for doing this @benjie

**Comment by benjie** [comment]
PRs raised; closing 👍
