### ISSUE TITLE
Is there a scheduled next meeting?

### ISSUE THREAD

**Issue by mike-marcacci** [graphql/graphql-wg#135]
I plan on pushing for [this RFC](https://github.com/facebook/graphql/pull/373) again, and need to resolve merge conflicts in the RFC and [reference implementation](https://github.com/graphql/graphql-js/pull/1218) but want to plan it so I don't have *more* conflicts to fix by the time people can look at it.

Has there been any out-of-band discussion about the next meeting? If so, could we get a new agenda item in the repo?

**Comment by binaryseed** [comment]
Anyone have an update on the next possible meeting?

**Comment by simPod** [comment]
@mike-marcacci any update on this? It's kinda blocker as most languages can implement multiple interfaces so the domain layer is usually designed like so it leverages that. 

And then when the domain layer is somehow mirrored into GQL schema, it's impossible to fully do that.

**Comment by mike-marcacci** [comment]
@simPod - unfortunately not.

It looks like @AGS- @jjergus @jspahrsummers and @RamonSaboya are associated with the GraphQL organization in GitHub. In the past, of course @leebyron has been the driving force behind GraphQL, at least as far as "us on the outside" are concerned.

If you need someone from the community to step up here and help lead, I would be willing to take that on. Like most everyone else here I'm quite busy with other projects and would rather not take on too much responsibility... but it's important to me that the spec maintains the high degree of thoughtfulness that's made it so useful, while not stagnating. What do you all think?

**Comment by leebyron** [comment]
Hey folks, sorry for the significant delay in WG meetings. Now that the foundation is up and running I'm getting these back on the books
