### ISSUE TITLE
[2023-08] full schemas: write a RFC that captures the WG discussion and a possible way forward

### ISSUE THREAD

**Issue by martinbonnin** [graphql/graphql-wg#1367]
Turns out https://github.com/graphql/graphql-spec/pull/1036 contained a small rabbit hole of how we want to represent schemas for consumption by different tools and the spec PR itself is a bit short to have a proper discussion.

This action item is to create a RFC document that we can evolve as we discuss the topic.

I can't commit to a timeline but I'll do my best. Feel free to garbage collect this if it becomes stale!

* assignee(s): @martinbonnin
* source: https://github.com/graphql/graphql-wg/blob/main/notes/2023/2023-08.md#sdl-omissions-martin

---
Note: Action Item issues are reviewed and closed during Working Group
meetings.

**Comment by martinbonnin** [comment]
@benjie I'd like to reuse that issue as an umbrella issue to keep track of other smaller tasks. Would that be possible? 

I just updated the description quite substantially, I hope it's OK? If that's OK, can we remove the `action item` label cause it's probably going to stick around for a while?

**Comment by benjie** [comment]
:+1: 

You might consider using the Discussions instead? https://github.com/graphql/graphql-wg/discussions

Entirely up to you.
