### ISSUE TITLE
[2023-10] Close all aging action items

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1413]
Action item #1349 has been open for a while now; so we've agreed to close all action items that have been open for at least 6 months without activity.

- assignee(s): @benjie
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2023/2023-10.md#review-previous-meetings-action-items-5m-lee

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by Rodipaun** [comment]
#1349

**Comment by benjie** [comment]
I marked all aging items with `stale` and have worked my way through them. Many of them have now turned into spec PRs and agenda topics; many are ready for review, and the remainder have been closed as stale due to lack of champion of lack of activity. This issue can now be closed.
