### ISSUE TITLE
[2023-10] Everyone - please review Full Schemas RFC

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1415]
Related:

- https://github.com/graphql/graphql-spec/pull/1049
- https://github.com/graphql/graphql-wg/discussions/1391

Martin is proposing that we formalize the concept of a "full schema document" - like our existing GraphQL SDL that represents a GraphQL schema, but one that reflects _every detail_ of the schema, including the introspection types, such that an arbitrary operation can be validated against the specific implementation of a schema.

Please take some time to review this.

- assignee(s): Everyone (champion @martinbonnin)
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2023/2023-10.md#full-schemas-15min-martin

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@martinbonnin Please reply to this comment (even a :wave:  is sufficient) so that I can assign you. Thanks!

**Comment by martinbonnin** [comment]
👋 Thanks for following up on this!
