### ISSUE TITLE
🗳 2024 Technical Steering Committee (TSC) Elections 🗳

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#1446]
# GraphQL TSC Elections 2024!

We're overdue for our TSC elections. Time to get things moving. We will announce and discuss in our next working group meeting, but please feel free to share this and nominate yourself and encourage others who may be good members to take a look and consider.

## Actions

cc @graphql/tsc 

- Read [TSC scope and responsibilities](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#scope).
- Self nominate in [this form](https://docs.google.com/forms/d/e/1FAIpQLSeXkaUoyQ1QXv9sPknYKpoYKzH6Wixg0eh4aAiKXGEH1kU_8Q/viewform?usp=sf_link).
- Read the voting process in our [TSC charter](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#election-dates).

## Dates

We're starting our elections process slightly late, so will be shifting the dates found in our [TSC charter](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#election-dates) by about a month.

| Term          | Nominations open | Voting open   | Term begins | Term ends    |
| ------------- | ---------------- | ------------- | ----------- | ------------ |
| 2024 - 2025   | Nov 30, 2023     | Jan 1, 2023   | No later than Feb 1, 2024 | Dec 31, 2025 |

Specifically, we're opening the nominations process now, and will keep them open through the end of the year and start the voting process on Jan 1.

If you are interested in joining the GraphQL TSC, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSeXkaUoyQ1QXv9sPknYKpoYKzH6Wixg0eh4aAiKXGEH1kU_8Q/viewform?usp=sf_link) to self-nominate.

## TSC members who's terms are expiring this year:

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Benjie Gillam](https://github.com/benjie)         | Graphile              | Nov 1, 2020 | Dec 31, 2023 |
| [Ivan Goncharov](https://github.com/IvanGoncharov) | Apollo                | Nov 1, 2020 | Dec 31, 2023 |
| [Marc-Andre Giroux](https://github.com/xuorig)     | Netflix               | Jan 1, 2022 | Dec 31, 2023 |
| [Matt Mahoney](https://github.com/mjmahone)        | Meta                  | Nov 1, 2020 | Dec 31, 2023 |
| [Michael Staib](https://github.com/michaelstaib)   | ChilliCream           | Jan 1, 2022 | Dec 31, 2023 |

## TSC members who will be voting this cycle:

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Lee Byron (chair)](https://github.com/leebyron)   | GraphQL Specification | N/A         | N/A          |
| [Andi Marek](https://github.com/andimarek)         | Atlassian             | Nov 1, 2020 | Dec 31, 2024 |
| [Kewei Qu](https://github.com/Keweiqu)             | Meta                  | Jan 1, 2023 | Dec 31, 2024 |
| [Rob Richard](https://github.com/robrichard)       | 1stDibs               | Jan 1, 2023 | Dec 31, 2024 |
| [Stephen Spalding](https://github.com/fotoetienne) | Netflix               | Jan 1, 2023 | Dec 31, 2024 |
| [Uri Goldshtein](https://github.com/urigo)         | The Guild             | Jan 1, 2023 | Dec 31, 2024 |

**Comment by leebyron** [comment]
Just to make sure notifications end up in the right places, starting by directly cc'ing @benjie @IvanGoncharov @xuorig @mjmahone @michaelstaib as those who may wish to self-nominate for continued terms.

**Comment by leebyron** [comment]
I'll let everyone here know that the nominations have been closed and I am starting an internal vote on and will update the outcomes in this thread. I'll wait for all voting TSC members to cast before closing, so thank you all for your patience.

**Comment by leebyron** [comment]
Thank you to everyone who participated in this voting cycle! We had 8 excellent nominees and just completed a TSC vote using [Meek STV](https://blog.opavote.com/2017/04/meek-stv-explained.html).

🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁

The TSC members voted into seat for this upcoming term (in alphabetic order):

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Benjie Gillam](https://github.com/benjie)         | Graphile              | Nov 1, 2020 | Dec 31, 2025 |
| [Denis Badurina](https://github.com/enisdenjo)     | The Guild             | Feb 1, 2024 | Dec 31, 2025 |
| [Ivan Goncharov](https://github.com/IvanGoncharov) | Apollo                | Nov 1, 2020 | Dec 31, 2025 |
| [Matt Mahoney](https://github.com/mjmahone)        | Meta                  | Nov 1, 2020 | Dec 31, 2025 |
| [Michael Staib](https://github.com/michaelstaib)   | ChilliCream           | Jan 1, 2022 | Dec 31, 2025 |

Congratulations for all of these folks, @benjie, @IvanGoncharov, @mjmahone, and @michaelstaib for continuation of their roles, and welcomie @enisdenjo who has been a proactive WG member for some time contributing to the HTTP and networking specifications and implementations. Thank you all for your commitment to keep the GraphQL project well organized and continuously improving.

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

Of course, we will continue to keep the set of TSC-only domain as narrow as possible, and encourage broad co-ownership over the GraphQL projects by all who wish to participate in the open Working Group meetings. This project wouldn't exist without the continuous support it gets from this great community.

**Comment by dondonz** [comment]
Congratulations!!!
