### ISSUE TITLE
[2024-02] EVERYONE - check that changing `SHOULD` to `MUST` for error paths won't break your implementations

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1482]
Ref: https://github.com/graphql/graphql-spec/pull/1073

This spec PR immediately jumped to RFC2 status as it already seems to be the status quo, but none the less since it's technically a breaking change (`should` -> `must`) we're passing it through the RFC process. We will be merging it in as stage 3 in the spec next month, unless you tell us why we shouldn't - so please check your implementations are compliant!

- assignee(s): Everyone (champion @martinbonnin)
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2024/2024-02.md#using-must-for-error-paths-5m-benoit

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@martinbonnin Please reply to this so I can assign you - thanks!

**Comment by martinbonnin** [comment]
👋
