### ISSUE TITLE
[2024-03] GraphQL library authors: last chance to comment on error path constraints moving from SHOULD to MUST

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#1499]
https://github.com/graphql/graphql-spec/pull/1073

We will be merging this at the next primary working group if no blocking reviews arise.

- assignee(s): @graphql/implementers (champion @martinbonnin)
- source: https://github.com/graphql/graphql-wg/blob/2b81dcd0eb600e5cb96427ce5864ea5d07965b63/notes/2024/2024-03.md#strict-error-paths-5m-martin

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@martinbonnin Please reply to this so I can assign you. Thanks!

**Comment by martinbonnin** [comment]
👋
