### ISSUE TITLE
Registration for graphql slack is down 

### ISSUE THREAD

**Issue by acao** [graphql/graphql-wg#169]
https://graphql-slack.herokuapp.com/ doesn't allow new registrations

it's linked to from the community docs: https://graphql.org/community/#slack-communities

i would have opened this in the documentation site repo, but this seemed more appropriate?

**Comment by orta** [comment]
If someone gives me access to the heroku instance ( `first.lastname@gmail.com` ) then I can fix this

**Comment by leebyron** [comment]
I just got you access @orta and @acao, hopefully you're able to unbreak it

**Comment by acao** [comment]
@leebyron thank you!

**Comment by benjie** [comment]
I just managed to sign up, so I think you can close this 👍

**Comment by acao** [comment]
it works only if you are logged into Slack already, to be sure

**Comment by acao** [comment]
@benjie confirmed, yes it does work anonymously now! thanks to whoever fixed it

**Comment by orta** [comment]
I updated it 👍
