### ISSUE TITLE
https://graphql.org SSL certificate has expired

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#176]
As reported by @kolobock in https://github.com/graphql/graphql-spec/issues/448#issuecomment-496516908

![Screenshot 2019-05-28 14 32 50](https://user-images.githubusercontent.com/129910/58482038-84b26d80-8155-11e9-9923-a270e191e87a.png)

**Comment by benjie** [comment]
@leebyron Tagging you as I suspect you'll know who to contact about this.

**Comment by caniszczyk** [comment]
fixed now, sorry about that
