### ISSUE TITLE
[2019-06-06] Schedule GraphQL.org meeting

### ISSUE THREAD

**Issue by dblandin** [graphql/graphql-wg#208]
Schedule 10-15m meeting to discuss where graphql.org is today and brainstorm action items

assignee: @tanaypratap 
source: [GraphQL Working Group Meeting 2019-07-03
](https://github.com/graphql/graphql-wg/blob/ffbbdbac74e3e957c1dba814704c08ff02c35353/notes/2019-07-03.md#action-items)

**Comment by tanaypratap** [comment]
@dblandin @IvanGoncharov how should I go about scheduling this meeting? What time works for everyone?

**Comment by tanaypratap** [comment]
@robzhu @BrunoScheufler @leebyron what would be an ideal time to setup this meeting and brainstorm. I have talked to the designer once and she would need vision to come up with something good.

**Comment by BrunoScheufler** [comment]
Good question, we should definitely think about timezones to make sure everybody can attend 🤔 Maybe we can choose a different day than Thursday so we don't interfere with any other wg meetings

**Comment by robzhu** [comment]
How about these time slots? http://www.needtomeet.com/meeting?id=lael78opV

**Comment by BrunoScheufler** [comment]
Both Tuesday and Wednesday would be great personally, what about the others?

**Comment by robzhu** [comment]
Looks like Tanay and I are available for all three slots, and Bruno indicated Tues/Wed. Let's do 8/27 10-11AM EST. Does that work for everyone else on the thread?

**Comment by tanaypratap** [comment]
We need Lee as well at least for the first meeting.

**Comment by robzhu** [comment]
@leebyron can you make any of those times?

**Comment by leebyron** [comment]
8/27 10-11AM EST Works for me

**Comment by robzhu** [comment]
@BrunoScheufler where should I send your invite? my email is robzhu at gmail

**Comment by BrunoScheufler** [comment]
@robzhu I've sent a mail to your address!

**Comment by Urigo** [comment]
Can I join as well?
(my email is public on my Github profile)
thank you

**Comment by praveenweb** [comment]
Did this meeting take place already? If so, would like to see the action items. Would love to contribute :)
