### ISSUE TITLE
[2019-07-03] Write up vision for code page

### ISSUE THREAD

**Issue by dblandin** [graphql/graphql-wg#209]
Write up vision for code page

assignee: @leebyron 
source: [GraphQL Working Group Meeting 2019-07-03
](https://github.com/graphql/graphql-wg/blob/ffbbdbac74e3e957c1dba814704c08ff02c35353/notes/2019-07-03.md#action-items)

**Comment by tanaypratap** [comment]
Linked to #208

**Comment by benjie** [comment]
I've seen a lot of work on the code page; this might not be relevant any more.

**Comment by dblandin** [comment]
> I've seen a lot of work on the code page; this might not be relevant any more.

Agreed! Following the awesome work from https://github.com/graphql/graphql.github.io/pull/936, I think we can go and close this issue 👍 🎉

**Comment by benjie** [comment]
Thanks for confirmation @dblandin :+1:  I believe the process is that we close these issues during GraphQL Working Groups, so I'm going to reopen it temporarily.
