### ISSUE TITLE
Create Q&A on most important details

### ISSUE THREAD

**Issue by dblandin** [graphql/graphql-wg#210]
Create Q&A on most important details (contents, etc.)

assignee: Unclaimed 
source: [GraphQL Working Group Meeting 2019-07-03
](https://github.com/graphql/graphql-wg/blob/ffbbdbac74e3e957c1dba814704c08ff02c35353/notes/2019-07-03.md#action-items)

**Comment by IvanGoncharov** [comment]
@tanaypratap I think @leebyron already has some plan for it since he created this repo:
https://github.com/graphql/faq

**Comment by guettli** [comment]
Where can new comers ask question about GraphQL? Please answer this question in the FAQ.

**Comment by dblandin** [comment]
Going to close this issue as https://github.com/graphql/faq is up and running :+1:
