### ISSUE TITLE
RFC for introspection field for spec information

### ISSUE THREAD

**Issue by dblandin** [graphql/graphql-wg#212]
RFC for introspection field for spec information

assignee: @eapache & @andimarek
source: [GraphQL Working Group Meeting 2019-07-03
](https://github.com/graphql/graphql-wg/blob/ffbbdbac74e3e957c1dba814704c08ff02c35353/notes/2019-07-03.md#action-items)

**Comment by eapache** [comment]
Myself (@eapache) and @andimarek are working on this.

**Comment by eapache** [comment]
It's not ready for review, but I'm cutting a very rough first draft of the spec changes at https://github.com/eapache/graphql-spec/tree/custom-scalar-formats.

**Comment by benjie** [comment]
@eapache Do you think we should address versioning of these custom scalar specification documents? I think it's mostly beyond the scope of the spec, except maybe it should state that non-trivial ("functionally significant"?) changes to the specification document should result in a new `specificationUri`? E.g. JSON -> JSON5 would break previous parsers, so should require a new URI? Presumably this also would mean that changing the `specificationUri` would be a breaking change.

**Comment by eapache** [comment]
That's a really good point, I'll work that in.

**Comment by eapache** [comment]
This action item is effectively done, the RFC exists and is nicely in progress https://github.com/graphql/graphql-spec/issues/635

**Comment by dblandin** [comment]
> This action item is effectively done, the RFC exists and is nicely in progress graphql/graphql-spec#635

Awesome! Going to go ahead and close this issue :tada:
