### ISSUE TITLE
Details about GraphQL Configuration for cross-tool usage in August 2019 meeting

### ISSUE THREAD

**Issue by navneet-g** [graphql/graphql-wg#225]
Apologies if creating an issue is not the right approach for my question.

I was going through the meeting notes for [August Meeting Notes](https://github.com/graphql/graphql-wg/blob/master/notes/2017-08-14.md#graphql-configuration-for-cross-tool-usage).

There is a mention of discussion around improvements for gateway services.

Where can I find details about the discussion and next steps?
For example proposals if any, scope, timelines.

Thanks,
Navneet

**Comment by IvanGoncharov** [comment]
@navneet-g It was August 2017 so I'm not 100% sure but I think we were discussing:
https://github.com/prisma/graphql-config
Sorry, can't remember anything else 🤷‍♂

**Comment by navneet-g** [comment]
My apologies ... I looked at the month, should have looked at year as well :).

**Comment by IvanGoncharov** [comment]
@navneet-g I also think it was a period when Apollo and a few other vendors were developing the first generation of GraphQL gateways.
So I would assume that `graphql-config` was the main topic and we just had a side discussion if it's possible to reuse it to configure gateways.

Is there anything else I can help?

**Comment by navneet-g** [comment]
Thanks @IvanGoncharov I was interested in knowing if something similar to [Apollo Federation](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/) specification is on the radar for the GraphQL spec.

**Comment by benjie** [comment]
Closing this issue as it appears to be stale.
