### ISSUE TITLE
Spec cut date?

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#261]
I'd like to start a discussion about when we should cut the next release of the GraphQL specification.

It has been 16 months since the last release, and some significant changes and iterative improvements have been made in that time. The previous two release have 20 months between them.

I'd like to return to an annualized and predictable schedule for specification releases.

**Comment by leebyron** [comment]
Looking at the current set of [proposals to the spec](https://github.com/graphql/graphql-spec/pulls), we have *6* stage 2 draft proposals.

An action for me as the spec editor is to review all of these and decide which need significant changes and which are ready to go with minor touch-ups.

I think we should be able to reach stage 3 with most, if not all of these proposals before cutting the specification. I'd like to do that before the end of the year.

**Comment by spawnia** [comment]
I think that this year would be a good time to make the release.

The current stage 2 proposals are either spec-only or have solid implementations backing them up. I don't see any stage 1's or stage 0's that are on the cusp of getting there.

**Comment by alexhancock** [comment]
Hello all, happy 2021.

I wanted to re-start this discussion. I am planning to read the spec soon, as GraphQL has become a major part of my work. I wondered how close the "Working Draft" is to an official version of the spec, and when a new official version may be cut?

**Comment by leebyron** [comment]
Sorry for the lack of updates on this issue! The process to cut an official version is a legal issue, not a technical one. 

For practical purposes, all reference implementations of GraphQL are encouraged to follow the working draft, and the vast majority do.

Official cut versions mark a legal sign off process milestone, and unfortunately for us we were not strict about this process in 2018 through mid 2020 and going back over the previous work has taken longer than hoped. The good news is that this process is nearly completed and we can wrap up the final pieces of the process this month.

**Comment by leebyron** [comment]
The bar for accepting changes into the working draft is very high, and in practice only editorial refinements occur between those changes and official cuts. If you're looking for a version to read to be up to date with where the technical community is, I would highly suggest reading the working draft - regardless of the legal process around official cuts.

**Comment by alexhancock** [comment]
@leebyron Thanks for the information and recommendation! I will read the working draft 👍

**Comment by leebyron** [comment]
Well 2020 was a year but we're wrapping up. Goal is to release in March 2021!

**Comment by benjie** [comment]
https://spec.graphql.org/October2021/
