### ISSUE TITLE
GraphQL over HTTP specification

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-wg#293]
We previously discussed the possibility of such spec and I went ahead and create MVP:
https://github.com/APIs-guru/graphql-over-http
It would be great if we adopt it under GraphQL Foundation as a complementary spec.
I'm still interested in collaborating but I would love if the community and industry leaders take a lead and we can form a subgroup to work on it.

**Comment by sjparsons** [comment]
Thanks for opening this @IvanGoncharov I'm interesting in being part of a subgroup around this topic.

**Comment by robzhu** [comment]
@IvanGoncharov I really like the direction of this proposal. I wonder how far the spec will go. For instance, will you be describing how to populate common HTTP Response headers? I'm also interesting in being part of this subcommittee.

**Comment by michaelstaib** [comment]
I am also really interested in this one.

**Comment by tinnou** [comment]
I'm interested as well. Let me know how I can help.

**Comment by abernix** [comment]
I'm also interested!

**Comment by ghmcadams** [comment]
I am also interested in participating in the sub group.

**Comment by IvanGoncharov** [comment]
I actually think this issue is a good place to discuss the time and date for the meetings. How about last Thursday of the month to not intersect with GraphQL WG?
So how about to 28th of November for a first call and use the same time as GraphQL WG which is 5PM UTC?
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=11&day=28&hour=17&min=0&sec=0&p1=224&p2=179&p3=136&p4=37&p5=239&p6=101&p7=152

**Comment by sjparsons** [comment]
I think in general that would be good time, except Nov 28 is Thanksgiving for people US; so I will be on holiday with family.

**Comment by IvanGoncharov** [comment]
@sjparsons Good catch 👍
How about November 21th for the first one?

**Comment by michaelstaib** [comment]
But let’s wait for the feedback of @robzhu before we settle for a date.

**Comment by mike-marcacci** [comment]
I'll definitely join this; the 21st would work for me.

**Comment by robzhu** [comment]
Nov 21 works for me

**Comment by benjie** [comment]
28th would not have worked for me, but 21st does :+1:

**Comment by ErikWittern** [comment]
Nov. 21st works for me as well.

**Comment by ghmcadams** [comment]
Who would like to create an agenda event (with a video conference link, agenda items, goals, etc.) for this?  I think it would help to get more people who are interested in that they can plan ahead.

**Comment by IvanGoncharov** [comment]
@ghmcadams Absolutely agree. I went ahead and created the agenda here:
https://github.com/APIs-guru/graphql-over-http/blob/master/agendas/2019-11-21.md

As I said during WG I want to give more power to the community on this one.
I still want to participate as a member and also help with technical stuff (repo management, Zoom, etc.) but it would be great for someone else to lead the discussion.

@sjparsons As a person who resurrected this topic. Do you want to lead a discussion about the first release of this spec its scope and action plan? If so can you please create PR that adds it to the agenda.

**Comment by sjparsons** [comment]
Thanks @IvanGoncharov, I'd be glad to lead the discussion. I'll submit a PR later today adding it to the agenda.

**Comment by IvanGoncharov** [comment]
СС: @leebyron @sjparsons @robzhu @michaelstaib @mike-marcacci @benjie @ErikWittern @ghmcadams @deinok  @jaydenseric @mmatsa @sjparsons @spawnia @sungam3r @xuorig @abernix @jbaxleyiii @DanielWoelfel @eapache @glennblock

It looks like everything is ready 🎉 
We will have a first call for the "GraphQL over HTTP" group this Thursday, Nov 21th at 5 PM UTC.
If you want to join in, please add yourself and your agenda items (if any) to the agenda:
https://github.com/APIs-guru/graphql-over-http/blob/master/agendas/2019-11-21.md
Also please feel free to invite other participants if you think they can contribute to the discussion.

**Comment by deinok** [comment]
I will try to be there

**Comment by benjie** [comment]
This is now adopted under the GraphQL Foundation: https://github.com/graphql/graphql-over-http/ I believe we can close this item at the next WG meeting (or now @IvanGoncharov?)

**Comment by glennblock** [comment]
Great to see that this has been incorporated into the foundation!

**Comment by IvanGoncharov** [comment]
@benjie Thanks for ping 👍
