### ISSUE TITLE
GraphQL @defer and @stream

### ISSUE THREAD

**Issue by Keweiqu** [graphql/graphql-wg#329]
We’ve been experimenting with @defer and @stream at Facebook for a while now  -- Lee first discussed the[ idea of @defer and @stream]( https://www.youtube.com/watch?v=ViXL0YQnioU&feature=youtu.be&t=9m4s) in 2016. Over the last three years, we've done a ton of iterations as we uncovered and resolved issues and edge cases following that initial approach. We're now seeing a renewed demand for these ideas in the open source community: 
https://github.com/graphql/graphql-js/pull/2318
https://github.com/graphql/graphql-js/pull/2319

Given that Facebook’s increased internal usage makes us more confident in our approach, it seems like a good time to start a discussion of what the next steps would be. Opening this issue with some strategic questions:
* What's the best way to drive @defer and @stream standardization?
* Should these features be part of the official spec or a supplemental specification (e.g.  connections)?
* If we decide these features are worthy of standardization, what's the best way of driving towards alignment? Should we set up a stream/defer focused-WG?

**Comment by leebyron** [comment]
Closing this issue since it's now a recurring agenda item!

**Comment by caass** [comment]
@leebyron is there somewhere i can keep up with the progress of `@stream` and/or `@defer`? Asking because this is the first result when googling "graphql @stream"

**Comment by n1ru4l** [comment]
Just wanna link this here (as this issue always pops up first in google):

[Official Feedback Issue for graphql.js defer & stream](https://github.com/graphql/graphql-js/issues/2848)
