### ISSUE TITLE
Schedule working session with Input Union RFC champions

### ISSUE THREAD

**Issue by binaryseed** [graphql/graphql-wg#378]
Our next step in the Input Union RFC process is to gather the individual solution champions for a working session where we can dive into the details of solutions and try to make some progress towards a proposed solution.

* https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md

Our aim is to have this meeting about 1 week before the next general Working Group meeting:
* https://github.com/graphql/graphql-wg/blob/master/agendas/2020-04-02.md

Current champions: @leebyron @binaryseed @eapache @benjie

**Comment by benjie** [comment]
I can't do that time unfortunately (I'm already double booked :confounded:). Could we push it back 2 hours - 18:00-21:00 UTC?

Alternatively the Monday and Tuesday before and after that date are currently wide open for me.

**Comment by eapache** [comment]
I'm free any of those times on the 26th. Monday/Tuesdays also mostly work for me.

What time zones are folks in? We might be able to find a more convenient time with a smaller group of time zones here than the full working group. I'm GMT-5.

**Comment by benjie** [comment]
I'm in UK, so GMT (UTC) until 29th March, BST (UTC+1) after.

**Comment by binaryseed** [comment]
I'm GMT-7

I can do 26th as well

**Comment by benjie** [comment]
Do we want to try and squeeze in a meeting before the Spec WG, or retry next month?

**Comment by eapache** [comment]
I think it's probably too late to try and squeeze something in at this point. The last month or so has been a bit of a mess for the entire world, so I'm not feeling particularly rushed to get this together, though a doodle poll or something might be nice to help us figure out a good time to meet?

**Comment by eapache** [comment]
(Also want to mention that I spent some time trying to fill in the gaps in https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md and found it really hard to ensure consistency between the various cross-referenced tables of criteria by solution and solution by criteria.)

**Comment by leebyron** [comment]
Closing this since we scheduled and met!
