### ISSUE TITLE
[MVP] GraphQL over HTTP

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-wg#39]
On the last WG we discussed "GraphQL over HTTP" spec and I've prepared a minimalistic draft:
https://gist.github.com/IvanGoncharov/021bdb39761e1c80b1fc698706b2ecf7

@leebyron But I'm not sure about the next steps.
Would you create "graphql/graphql-over-http" repo so I can submit this Draft as a PR?
Or should I create a personal repo and then move it afterward?

**Comment by leebyron** [comment]
I think it makes sense for you to create a repo in your account to begin the editing process, that way you can manage PRs and discussion in that repo. Once it has become fully formed, then we can consider moving it into this top level org as a sort of way of ratifying it.

**Comment by IvanGoncharov** [comment]
@leebyron Agree 👍
I created: https://github.com/APIs-guru/graphql-over-http

**Comment by deinok** [comment]
@IvanGoncharov Should we start working on this spec and tag all the interested people that is writing graphql libraries for HTTP?

**Comment by IvanGoncharov** [comment]
@deinok It was discussed here:
https://github.com/graphql/graphql-wg/blob/master/notes/2018-02-01.md#next-steps-for-graphql-over-http-spec

And there were some concerns voiced during discussion so draft should be updated to address them. ATM, I'm focused on releasing `graphql-js@14.0.0` but it's one of the top items on my TODO list.
If you have more questions or want to help please open an issue in this repo:
https://github.com/APIs-guru/graphql-over-http
