### ISSUE TITLE
[2020-05-07] introspection shortcuts RFC: describe the problem

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#425]
Discuss RFC adding introspection shortcuts to determine full typename and named type’s name (15m, Terrence)

[ACTION - Terrance] - describe the problem, look at the landscape of potential solutions, and figure out which ones are appropriate or not

https://github.com/graphql/graphql-wg/blame/master/notes/2020-05-07.md#L67

**Comment by benjie** [comment]
@chemisus Are you interested in following up on this topic?

**Comment by chemisus** [comment]
@benjie Yes, I am.

**Comment by benjie** [comment]
@IvanGoncharov / @leebyron Please assign this to @chemisus

**Comment by benjie** [comment]
@chemisus Did you get anywhere with this? Are you still interested in following up?

**Comment by benjie** [comment]
We'll be closing this during the next working group if no further progress is noted; we can always open a replacement issue when you have available time :+1:
