### ISSUE TITLE
[2020-05-07] Include defer/stream problem statements in RFC doc

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#428]
https://github.com/graphql/graphql-wg/blame/master/notes/2020-05-07.md#L168

**Comment by leebyron** [comment]
I believe this was handled by https://github.com/graphql/graphql-spec/pull/717 - is there more to do @robrichard ?

**Comment by robrichard** [comment]
@leebyron I believe all the points discussed are covered in the RFC now. Thanks!
