### ISSUE TITLE
[2020-09-03] GitHub infrastructure for managing Working groups

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-wg#477]
How other working groups should be managed on GitHub?

**Comment by benjie** [comment]
I believe this relates to the following item from [the TypeScript Migration / bootstrap GraphQL-js WG / GitHub infrastructure discussion](https://github.com/graphql/graphql-wg/blob/b1bfe0cee461d752146dc77e5c35a5e8d7921272/notes/2020-09-03.md#typescript-migration-progress-in-graphql-js-5m-dotan-how-to-bootstrap-graphql-js-working-group-5m-dotan-github-infrastructure-for-managing-working-groups-10m-ivan):


ACTION - Ivan; Ivan: I can create a repo and add you there; copy structure of GraphQL WG.

**Comment by Urigo** [comment]
update: 
I've just set up a copy of the structure @benjie has been leading in the graphql-js WG: https://github.com/graphql/graphql-js-wg/pull/1
and opened issues for action items here: https://github.com/graphql/graphql-js-wg/issues

I wasn't able to do exactly everything for the lack of permissions but it's a step closer

**Comment by benjie** [comment]
@Urigo Do you want me to add this for review at next WG, or hold off until the extra things requiring permissions are addressed?

**Comment by Urigo** [comment]
Yes let's add it for review, I'm sure the rest of the stuff are minor and would be solved on the next day or two

**Comment by leebyron** [comment]
Note from meeting: Next step on me to write a proposal for how to evolve the graphql-wg directory structure
