### ISSUE TITLE
[2020-09-03] Call to organize collaboration on TypeScript migration of GraphQL.js

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#485]
> Ivan: TypeScript migration will be a breaking change. Let's discuss it on a call since not everyone's interested in JavaScript implementation. I think it's important to allow new contributors; Flow is a barrier for many people to contribute. TypeScript is easier, I've heard from many contributors.
> [...]
> Dotan: any issues, if you need help, we can put people to work on it with you. If you need help, we are here.
> ACTION - Ivan - organize a call with Dotan to figure out a strategy.

- assignee(s): @IvanGoncharov @dotansimha 
- source: https://github.com/graphql/graphql-wg/blob/b1bfe0cee461d752146dc77e5c35a5e8d7921272/notes/2020-09-03.md#typescript-migration-progress-in-graphql-js-5m-dotan-how-to-bootstrap-graphql-js-working-group-5m-dotan-github-infrastructure-for-managing-working-groups-10m-ivan

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
This was also raised as an action in August

https://github.com/graphql/graphql-wg/blob/master/notes/2020-08-06.md#typescript-migration-plan-progress-and-next-steps-10m-dotan

**Comment by Urigo** [comment]
Update:
We've had the first graphql-js working group and the next step for this item is mostly on the [following action item](https://github.com/graphql/graphql-js-wg/issues/7)
