### ISSUE TITLE
[2020-09-03] Contact Matt about Flow support in TypeScript version of GraphQL.js

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#486]
> Ivan: I should also contact Matt about Flow support because we need to figure out how to migrate to TypeScript without breaking Flow clients (at Facebook specifically)

- assignee(s): @IvanGoncharov 
- source: https://github.com/graphql/graphql-wg/blob/b1bfe0cee461d752146dc77e5c35a5e8d7921272/notes/2020-09-03.md#typescript-migration-progress-in-graphql-js-5m-dotan-how-to-bootstrap-graphql-js-working-group-5m-dotan-github-infrastructure-for-managing-working-groups-10m-ivan

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
Note: this was not explicitly marked as an action item during the WG, so please feel free to close it if it's inappropriate.

**Comment by IvanGoncharov** [comment]
We discussed it during the `graphql-js` WG call and @dotansimha @Urigo volunteered to help with maintaining Flow typings. That resolves my main concern about Flow support since we finally have enough volunteers to maintain them.
