### ISSUE TITLE
[2020-09-03] Update @defer/@stream RFC with more thorough explanation of fragments vs fields

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#487]
Discussion related to limiting @defer/@stream to only fragments vs also allowing it on fields. This was explained well in WG, Rob agreed to add it to the RFC

> ACTION - Rob: Rob: I'll update the RFC PR with a more thorough explanation and then we'll get that into the spec as well. 

- assignee(s): @robrichard 
- source: https://github.com/graphql/graphql-wg/blob/b1bfe0cee461d752146dc77e5c35a5e8d7921272/notes/2020-09-03.md#deferstream-15m-robliliana

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by robrichard** [comment]
I have updated this PR with the points discussed in the WG meeting: https://github.com/graphql/graphql-spec/pull/774

**Comment by benjie** [comment]
This was discussed during the 2020-11-05 WG here:

https://github.com/graphql/graphql-wg/blob/master/notes/2020-11-05.md#defer-and-stream
