### ISSUE TITLE
[2020-09-03] Create PR merging policy and grant more contributors maintainer access to WG repo

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#489]
> Ivan: if we write a document with policies, we can have more people help with merging.
> Lee: we can be more liberal with giving merge access to the WG repo. Anyone who's a frequent guest of these meetings we can give commit access to.
> Ivan: especially the champions. You just promise to not merge anything in other people's RFCs, only in your RFC.
> ACTION - Lee: make this happen

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/b1bfe0cee461d752146dc77e5c35a5e8d7921272/notes/2020-09-03.md#any-other-business

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Notes on how to resolve this from 9/2021 meeting:

Intent was to allow more people access to the RFC files while keeping maintenance tight on the spec itself.

TODO:
* [ ] Move rfc directory into this working group repository
* [ ] Add a high level markdown file (README?) which explains PR merging policy

**Comment by leebyron** [comment]
Just added @graphql/wg-core to expand maintenance
