### ISSUE TITLE
[2020-08-06] Clarify the problem that Field Coordinates is addressing

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#493]
> Lee - For RFC to move forward, need to be clear about what problem we’re solving. Specify what this is for, and what this is not intended to be used for.
> [ACTION - Mark] - clarify the above

- assignee(s): @magicmark 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2020-08-06.md#field-coordinates-rfc-15m-mark

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by magicmark** [comment]
ack - got a draft going to revise the RFC!

**Comment by benjie** [comment]
The meeting notes now have a link to the YouTube recording of the meeting in case it helps :+1:

**Comment by magicmark** [comment]
I've updated the problem statement in theand added some (hopefully) extra crispy use cases :)

https://github.com/graphql/graphql-spec/pull/746


Still working on a full breakdown of the spec (not sure how implementation detaily to get at this stage), but hopefully I've addressed this specific issue.

Thanks!
