### ISSUE TITLE
[2020-07-02] Require Argument Uniqueness

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#505]
> Ivan: validation for type system in chapter 3 requires uniqueness of type names, field names, etc; but we forgot to specify arguments were unique. It's not an editorial change, but pretty uncontroversial.
> Lee: on the topic of having a process; we need to have a reference implementation before calling it final stage.
> [...]
> ACTION - Ivan - implement in GraphQL.js

- assignee(s): @IvanGoncharov 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2020-07-02.md#review-previous-meetings-action-items-5m-lee 

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by IvanGoncharov** [comment]
`graphql-js` is in feature freeze due to TS conversion.
I will work on it after `16.0.0` release.

**Comment by benjie** [comment]
@IvanGoncharov does this need a GraphQL Spec edit? If so it seems wise to slip this in before the spec cut.

**Comment by benjie** [comment]
Adding Ready for review for us to discuss at the next WG; this might not be ready to actually close.

**Comment by benjie** [comment]
We're okay doing the spec changes for this (if any) after the spec cut if need be.

**Comment by benjie** [comment]
@IvanGoncharov to create the PR, hopefully by the next GraphQL Spec Working Group. Otherwise ask someone else to champion it.

**Comment by IvanGoncharov** [comment]
Created both PRs:
- Spec: https://github.com/graphql/graphql-spec/pull/877
- graphql-js: https://github.com/graphql/graphql-js/pull/3208

**Comment by IvanGoncharov** [comment]
Sadly can't traveling today.
So can't represent it on WG.
@benjie Can you add it to the agenda, since it looks like it's totally non-controvelsial.
