### ISSUE TITLE
[2020-07-02] Moving the @deprecated directive on Input Fields RFC to Stage 2

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#507]
> [ACTION - Lee] - Add RFC 2 tag to PR
> [ACTION] - Add SHOULD statement to spec recommending that it is generally ill-advised to add @deprecated to a non-null argument or input field unless there is a default value provided.
> [ACTION] - merge spec PR to master
> ~~[ACTION - Ivan] - Add schema validation to GraphQL.js that enforces @deprecated on nonnull~~ Moved to #518
> ~~[ACTION - Evan] - talk to Shopify team and others to determine SHOULD vs MUST.~~ Moved to #517

- assignee(s): ─
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2020-07-02.md#moving-the-deprecated-directive-on-input-fields-rfc-to-stage-2-15m45m-stephen

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
Sorry that's a lot of actions; we can absolutely split them up but I'm trying to get them filed before the WG :grimacing:

**Comment by eapache** [comment]
(my part of this was completed in August)

**Comment by benjie** [comment]
Thanks; separated out to #517 :+1:

**Comment by benjie** [comment]
I'm not sure exactly what the state of this is; https://github.com/graphql/graphql-spec/pull/525 has RFC1 and is merged; perhaps it was jumped up a couple RFC levels without the label being changed? Either way, I think this is ready for review.

**Comment by benjie** [comment]
@IvanGoncharov says he needs to check a small validation rule to make sure this is completely ready.
