### ISSUE TITLE
Google Summer of Code 2021

### ISSUE THREAD

**Issue by brianwarner** [graphql/graphql-wg#522]
Google has announced the timeline for [Summer of Code](https://summerofcode.withgoogle.com/). The format has changed somewhat for next year, in that timelines are shorter, projects are smaller, and the pool of candidates is expected to be broader.

Organizational applications begin January 29, 2021 and close February 19, 2021. If your project is interested in being included in a consolidated GraphQL application, please comment here.

**Comment by IvanGoncharov** [comment]
@brianwarner I liked GSoC this year and it was a great learning experience on how to onboard new contributors.
So happy to be a mentor for `graphql-js`, `express-graphql` and `graphql-over-http` projects.
