### ISSUE TITLE
[TSC] Process: if a TSC member raises a PR, does that count as an approval?

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#538]
From ["Making changes to this document"](https://github.com/graphql/graphql-wg/blob/master/GraphQL-TSC.md#making-changes-to-this-document) (emphasis mine):

> Pull requests against this document that do not conflict with the [Technical Charter](https://github.com/graphql/foundation/blob/master/GraphQL%20Specification%20Membership%20Agreement%20February%202019.pdf) can be merged provided the following conditions have been met:
>
> * There are no outstanding objections
> * There are **two approvals by TSC members**
> * The PR has been open for at least 72 hours

Currently #536 is open, raised by @leebyron, with approval from one other TSC member (myself). On GitHub you cannot "approve" your own PRs, so my question is this: does a TSC member raising a PR count as an implicit approval, or should we avoid ambiguity by changing the middle bullet above to something like:

> * There are two approvals by TSC members (excluding the PR author)

**Comment by leebyron** [comment]
Great question! Two approvers, not including the author. This is how most other TSC operate - the goal is to make sure multiple people have had a chance to see the change, regardless of who the author is.

I can add a clarifying message to this line!
