### ISSUE TITLE
[2020-11-05] Give feedback on the Schema Coordinates suggested GraphQL Spec Appendix

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#542]
> - Mark: as a reminder, the elevator pitch: in various GraphQL projects we need to refer to components of the schema, e.g. field name on a type, we commonly write this as e.g. `User.name`. There's no official convention, but tooling uses this convention, so this RFC tries to standardize and extend this syntax (e.g. referring to arguments)
> - Great reviews so far, especially from Ivan
> - What's the next steps?
> - Lee: **ACTION - everyone**: take a look at the appendix and reply with detailed feedback

https://github.com/graphql/graphql-spec/pull/746

- assignee(s): everyone; spearheaded by @magicmark 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2020-11-05.md#schema-coordinates

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@magicmark Please could you comment on this issue [so that I can assign you](https://github.blog/2019-06-25-assign-issues-to-issue-commenters/)? A simple :+1:  will suffice :wink: 

(It was noted in the WG yesterday that when a task is for everyone, it should be assigned to the person spearheading the effort to solicit feedback.)

**Comment by magicmark** [comment]
@benjie sorry I totally missed this!

Yes chef!
