### ISSUE TITLE
[2020-11-05] Update agendas to recommend adding GitHub username

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#543]
> - Benjie: can we add people's GitHub username to the agenda template to make it easier to tag in action items?
> - Lee: love that idea; I'll get on it
> - **ACTION - Lee**: update the agendas to recommend adding GitHub username, and to add yours to the attendees table.

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2020-11-05.md#any-other-business

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
* [ ] Add a column for this
