### ISSUE TITLE
[2020-10-01] Send removal notices to existing GraphQL.js contributors

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#550]
> Ivan: Maybe we should have a rule that if someone has not contributed for a year, we should send them a notice to ask if they want to continue - if they've not responded within a reasonable time (or decline), we should remove them. Is that reasonable?
> Lee: yes.
> Ivan: one year?
> Lee: yes. Some projects are on a slow cadence, so a year seems reasonable. You can also use your own judgement.
> ACTION - Ivan - send notices to existing contributors to GraphQL.js
> ACTION - Ivan/Uri - write a template for this notice to be polite with good explanation.

- assignee(s): @IvanGoncharov @Urigo 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2020-10-01.md#graphql-js-working-group-short-update-5m-uri

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
Edited to add @Urigo for the second action, since really these are one action I feel?

**Comment by Urigo** [comment]
Should we iterate on the notice content here?

**Comment by benjie** [comment]
> If item 550 is still open next meeting, we'll do "the fast way" - so we'll remove contributors who have not contributed in over (a year?)
> -- https://github.com/graphql/graphql-wg/blob/master/notes/2021-01-07.md#review-previous-meetings-action-items-5m-lee

**Comment by benjie** [comment]
@leebyron is going to clear up GraphQL organization access, @IvanGoncharov is going to clean up the graphql-js access.
