### ISSUE TITLE
[2021-01-07] Schema Coordinates: Add functions to graphql-js for schema coordinate parsing/printing

### ISSUE THREAD

**Issue by magicmark** [graphql/graphql-wg#581]
Add functions to graphql-js for schema coordinate parsing/printing

- assignee(s): @magicmark 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2021-01-07.md#discuss-schema-coordinates-spec-10m-mark

---

> Lee: regarding reference implementation changes, we should add at least parsing functions to allow parsing into an AST and printing an AST back out again. That would give people the tools they need to use this; and I think that's needed for RFC2.
> Lee: another (not required to move it to RFC2) would be to have a function that you pass a schema reference to and get a schema coordinate out.
> Lee: another: given a schema and a schema coordinate, return out the thing that that schema coordinate refers to. Also not required for RFC2.
> Lee: the parse/print will help us write tests and ensure we've dotted the i's and crossed the t's.
> ACTION - Mark - implement the print/parse functions.

**Comment by leebyron** [comment]
Added in https://github.com/graphql/graphql-js/pull/3044
