### ISSUE TITLE
[2021-01-07] Make initialCount nullable (GraphQL.js and spec)

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#588]
> In `@stream` we have the `initialCount` argument (required)
> Benjie suggests that we make it optional with default `0`
> [...]
> ACTION - Rob - update for `initialCount`; validation rule in GraphQL.js and the spec.

`@defer`/`@stream` spec edits: https://github.com/graphql/graphql-spec/pull/742

- assignee(s): @robrichard 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2021-01-07.md#deferstream-updates-10m-rob

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@robrichard  Please could you comment on this issue (and ping me) [so that I may assign it to you](https://github.blog/changelog/2019-06-25-assign-issues-to-issue-commenters/)? A simple "@benjie :wave:" will do :+1:

**Comment by robrichard** [comment]
👍

**Comment by robrichard** [comment]
@benjie I have updated the [Spec PR](https://github.com/graphql/graphql-spec/pull/742/commits/df363c7fa7513638b198070d366e4d2d05583fd1) and [GraphQL.js branch](https://github.com/graphql/graphql-js/pull/2839/files#diff-bb2ce423addd6bac025ea0843f740e6f9bf6a03075aa681a897b37a7fd015e93R214-R216) to reflect this change.
