### ISSUE TITLE
[2021-01-07] Everyone: review the @defer/@stream spec edits

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#589]
> ACTION - everyone - eyes on the RFC please!

Spec edits for `@defer`/`@stream` Spec PR: https://github.com/graphql/graphql-spec/pull/742

- assignee(s): everyone (assigned to @robrichard to spearhead)
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2021-01-07.md#deferstream-updates-10m-rob

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@robrichard  Please could you comment on this issue (and ping me) [so that I may assign it to you](https://github.blog/changelog/2019-06-25-assign-issues-to-issue-commenters/)? A simple "@benjie :wave:" will do :+1:

**Comment by robrichard** [comment]
👍
