### ISSUE TITLE
[2021-01-07] Discuss options for alternative meeting times

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#590]
It was discussed that the current meeting time is extremely inconvenient for people in various timezones including Australia, New Zealand and Asia. It was suggested that alternating times or finding a better pattern might make the Spec WG more accessible. It was noted that just changing the time would not be enough, since that would just make the time inconvenient for another set of people. @andimarek is to figure out what options we have.

> ACTION - Andi - open a GitHub issue and discuss the options there.

- assignee(s): @andimarek 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2021-01-07.md#alternative-meeting-time-5m-andi

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@andimarek feel free to use this issue for this discussion if you wish.

**Comment by andimarek** [comment]
I am located in Australia and the current time is 4 am which simply not great.

Moving it to 2h ahead it would set the meeting at 6am, which is still not great, but much better.

But as noted above: there is no perfect for everybody around the world. 6am in Australia would mean midnight in India for example. 

I propose to rotate the time to make at least every 3rd or so meeting acceptable for every time zone.

**Comment by benjie** [comment]
@andimarek Would you like to propose a concrete schedule to make discussion easier?

**Comment by benjie** [comment]
(Advise that you start the adjusted schedule in June/July to give a few months warning.)

**Comment by andimarek** [comment]
So here is my suggestion: I picked four different cities:  San Francisco, Berlin, New Delhi and Sydney.


| San Francisco | Berlin | New Delhi | Sydney| Comment |
----| --- | --- | ---|--- |
| 09:00am| 06:00pm | 10:30pm | 04:00am| Ok for SF and Berlin
| 02:00pm| 11:00pm | 03:30am | 09:00am| Ok for SF and Sydney
| 12:00am| 09:00am | 01:30pm | 07:00pm| Ok for Berlin and New Delhi

There is a lot we can iterate over, but SF and Berlin got two suitable times, while Sydney and New Delhi got each one. 

Again: this is the starting point for a discussion in the next WG meeting.

**Comment by benjie** [comment]
Here's a timeanddate.com for San Fran, London, Berlin, New Delhi, Sydney and New York for the April WG: https://www.timeanddate.com/worldclock/meetingtime.html?iso=20210401&p1=224&p2=136&p3=37&p4=176&p5=240&p6=179

**Comment by michaelstaib** [comment]
@andimarek the second would also still be manageable for us in CET. I would be OK with all of them if it helps you to attend.

**Comment by leebyron** [comment]
Closing this issue since we did push the call time by 2 hours. We can always bring this back up in the future
