### ISSUE TITLE
[2021-01-07] Research data collection techniques for finding a good time/set of times for Spec WGs

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#591]
Regarding #590:

> ACTION - Lee - find out if there's a great way to collect this input (worst case, google form); use this to inform choice.

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/master/notes/2021-01-07.md#alternative-meeting-time-5m-andi

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
I'm making a change for the April session based on the conversation that led to this action item, but for a sense of why this is a hard problem:

https://www.timeanddate.com/worldclock/meetingtime.html?month=4&day=1&year=2021&p1=224&p2=179&p3=136&p4=268&p5=367&p6=438&p7=240&iv=0
