### ISSUE TITLE
Change primary branch from master to main

### ISSUE THREAD

**Issue by brianwarner** [graphql/graphql-wg#598]
Everyone, we're going through the process of migrating the primary branch from `master` to `main`. GitHub has tools to migrate, which will also migrate any open PRs (currently there aren't any). 

However, if you've cloned this repo locally, you'll need to update your remotes. The easiest thing to do (assuming you aren't working locally) is just to delete your local files and re-clone this repo.

We'll make the change at some point after the next working group meeting.

**Comment by sungam3r** [comment]
Why is this necessary?

**Comment by brianwarner** [comment]
A number of open source projects have made this (minor) change in an effort to phase out certain English terms. `main` has emerged as the de facto replacement for `master`, and is also now the default for new GitHub repos.

There was discussion about this during recent foundation and working group meetings, and it came up again in Slack a few days ago. I volunteered to help with the process, and fortunately it's pretty easy and transparent with the tools that are available.
