### ISSUE TITLE
[2021-02-04] Update Foundation spec membership agreement

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#634]
> **ACTION** - Brian: graphql/foundation github repo, has [v4 of the JDF file](https://github.com/graphql/graphql-wg/blob/master/membership/GraphQL-Specification_Membership-2021-01-25-PREVIEW.pdf)

- assignee(s): @brianwarner 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-02-04.md#tsc-meeting-15m-brian-lee-tsc-members
---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
I believe @brianwarner addressed this the very next day.

**Comment by brianwarner** [comment]
That's right! And today is the last day of the waiting period for the docs to go fully active.
