### ISSUE TITLE
[2021-02-04] Update WG README to link to new membership agreement folder

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#635]
> **ACTION** - Lee: GraphQL WG readme file links to the foundation repo; link to new folder with explainer. [COMPLETE]

I believe this was actually completed during the WG session itself, so can probably be insta-closed.

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-02-04.md#tsc-meeting-15m-brian-lee-tsc-members

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by brianwarner** [comment]
This one is done as well. Instead of linking directly to the agreement without explanation, we now have a `membership` directory that contains step-by-step instructions for how to sign the docs as a company or as an individual. I'd say we can close this.
