### ISSUE TITLE
[2021-02-04] Everyone: think of GSoC project ideas

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#636]
>  **ACTION** - everyone (champion: Lee?): think about what potential projects there are.
>   We can consider things that are core parts of the GraphQL community - not just foundation projects
> [...]
> there's a channel in the slack; and the link in the agenda (https://github.com/graphql/foundation/tree/main/mentorship/2021/gsoc) is to a project template. Copy the template, fill out the idea (doesn't have to be super in depth) and save it as a markdown file in that folder (raise a PR).

- assignee(s): EVERYONE! (@leebyron as champion)
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-02-04.md#google-summer-of-code-this-year-5m-brian

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by brianwarner** [comment]
The application for GSoC has closed and we applied for a few projects... but... Google Season of Docs is open! This is how Carolyn got involved! I'll create a file to collect applications again.
