### ISSUE TITLE
[2021-02-04] Ensure all the CLAs and copyright notices in GraphQL repos are up to date

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#640]
> [291](https://github.com/graphql/graphql-wg/issues/291): Updating CLAs and copyright notices in GraphQL repos
> Lee: Will take this as an action item.
> **ACTION** - Lee: comb through with Brian to make sure these have all been dealt with.
> Morris mentioned a missing CLA (dead link) but I missed the refere

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-02-04.md#review-previous-meetings-action-items-5m-le

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by brianwarner** [comment]
I believe we're partially done here. I went through all of the repos and opened up PRs to add consistent instructions on how to sign the CLA, and then enabled the tooling.

I haven't checked the copyright notices for all repos, but we could cover this in the next working group meeting? It's super straightforward, but sometimes it helps to talk it through if there are questions.
