### ISSUE TITLE
[2021-03-04] Check that the LF calendar has correct time

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#641]
> Lee: heads up, we're trying to shift times to be more amenable to the asia timezone. Next time is shifted 2 hours plus potentially daylight savings differences too. It's updated in the Linux Foundation calendar.
> Evan: the LF calendar seems to show the old time.
> **ACTION** Lee: I'll follow up with Brian

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-03-04.md#new-meeting-time-2m-lee

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
Sidenote: why is the calendar not linked on https://graphql.org/community/upcoming-events/ ?

**Comment by benjie** [comment]
Marking this as ready for review because it appears to be 2 hours later to me.

**Comment by brianwarner** [comment]
I think we should be in good shape, I set the calendar entry to the new time and pegged it to UTC (so the upcoming DST changes probably(?) won't change the time except for timezones that still do this ridiculous nonsense).

Good point about graphql.org, though - we should add a link to [calendar.graphql.org](https://calendar.graphql.org).

**Comment by brianwarner** [comment]
@eapache It's definitely possible, there was an old calendar and a new calendar. The old one was (I think?) attached to Lee's personal gmail account. We moved it over to a Foundation calendar instead. The new one has "linuxfoudnation.org" in the url, and it's what you see if you go to [calendar.graphql.org](https://calendar.graphql.org).

I can add you to the new invite, along with anybody else who wants it. Once you're on the invite you can also add others, too, so we probably just need to get to critical mass.

**Comment by brianwarner** [comment]
Also @benjie, I spent some time this week porting the Foundation site over to graphql.org. I'll add this to the events section while I'm at it.

**Comment by eapache** [comment]
👍 I do have the new calendar too, and that one looks fine. If there's a way to delete the old calendar (which I linked in my previous comment) that would probably help in reducing confusion.

**Comment by benjie** [comment]
Ref #663
