### ISSUE TITLE
[2021-03-04] Implementors: make sure change to Default Value Coercion Rules is compatible

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#645]
[RFC](https://github.com/graphql/graphql-spec/pull/793) was moved from proposal to Draft

> **ACTION** - We need to make sure that when applied to existing impls that this works

- assignee(s): Implementors (champion @benjie)
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-03-04.md#rfc-default-value-coercion-rules-15m-benjie

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@leebyron It would be really helpful to have an `@graphql/implementors` or similar group that we can ping the relevant people behind the various GraphQL implementations (after they opt-in, of course).

**Comment by eapache** [comment]
cc @rmosolgo

**Comment by leebyron** [comment]
Created https://github.com/orgs/graphql/teams/implementers/

**Comment by leebyron** [comment]
@graphql/implementers - I'd love your feedback on this 

See related change here: https://github.com/graphql/graphql-js/pull/3049

**Comment by spawnia** [comment]
I hit this issue in graphql-php and am happy to see it moving forward. The proposed solution makes sense to me.
