### ISSUE TITLE
[2021-03-04] Implement Oneof Input Objects in GraphQL.js

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#648]
[RFC PR](https://github.com/graphql/graphql-spec/pull/825)

> **ACTION** (Benjie) - Write an implementation in GraphQL.js

- assignee(s): @benjie 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-03-04.md#rfc-oneof-input-objects-and-oneof-fields-30m-benjie

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by erikkessler1** [comment]
Hey @benjie, I've been following your Oneof RFC and some of the discussions around it in the GraphQL Working Group. I'm excited about the proposal and want to help move the RFC forward. I have experience with GraphQL and TypeScript, so I'd be interested in helping write an implementation for GraphQL.js. Did you already have an implementation in progress or should I just start from scratch? Also, from this [this comment](https://github.com/graphql/graphql-spec/pull/825#issuecomment-931096433), it sounds like you're still working through the syntax—do you have any thoughts on which syntax would be best to implement? Please let me know how I can help!

**Comment by benjie** [comment]
Hey @erikkessler1; that's great! There's a few open questions:

1. Which things will we support: input object types, object types, field arguments?
2. What's the syntax?

I think it's fine to drop field arguments ("Oneof Fields" in the spec edit) and go with just object types and input object types. I think it's also wise to simply use the directive syntax for now - at least then we can play with it :) There's quite a bit of pushback on using @oneof with output types (due to interfaces and unions already existing) but I'd like to see it implemented and then we can turn it off if we must to get it merged.

I don't have an in progress PR currently, I was planning to start work on it in February/March, got a few other things to clear off my plate first.

**Comment by erikkessler1** [comment]
Starting with input object types and object types using the directive syntax makes sense to me. I'll see what I can do working off of those assumptions!

**Comment by erikkessler1** [comment]
Hey @benjie, I've got some initial progress to share that I'd love to get your early feedback on. For consumability, I've broken my implementation into a few PRs on my fork of `graphql-js`:

* Type Additions: https://github.com/erikkessler1/graphql-js/pull/1
* Validation: https://github.com/erikkessler1/graphql-js/pull/2
* Execution: https://github.com/erikkessler1/graphql-js/pull/3

(The combined diff is [here](https://github.com/erikkessler1/graphql-js/compare/main...erikkessler1:oneof-execution))

Let me know your thoughts or what next steps I should take.

**Comment by benjie** [comment]
Excellent work; I didn't see anything in the changes that didn't align with my intent. I've not had time to fully review (I need to get back to doing the spec edits at some point!) but it's looking good to me :+1:

**Comment by erikkessler1** [comment]
Great, thank you for taking a look! Are there any other immediate action items you can think of for me?

**Comment by benjie** [comment]
Nope; just try it out in a real schema and see how you get on! 🙌

**Comment by nazreen** [comment]
any updates on this? :) we have a use case that could benefit from this solution

**Comment by benjie** [comment]
The RFC has been updated to drop Oneof Fields, I still need to find some time to test @erikkessler1's work above though. Have you tried it @nazreen?

**Comment by benjie** [comment]
“Oneof fields” are fields that accept one argument. The general feeling is that the goal is easy to achieve by using a oneof input object as the type of the only argument, and that not doing this limits schema evolution options. I’ve thus removed them.

The main reason to consider them is syntax; where does the directive/keyword/etc go?

**Comment by benjie** [comment]
Thanks to your work @erikkessler1, we've moved `@oneOf` to RFC2! :raised_hands:
