### ISSUE TITLE
[2021-04-01] Why were we declined for GSoC? Should we apply for GSoD?

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#661]
Ivan noted that GraphQL as an organization (not any specific project) was declined from GSoC this year. Since applications take time, Ivan wanted to know what the reason for this was (if we can find out) so we can determine if it's worth investing time in applying for GSoD or not.

- assignee(s): @brianwarner 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-04-01.md#review-previous-meetings-action-items-5m-lee

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Follow up here is we're going to plan for GSoC/GSoD with more advance timing
