### ISSUE TITLE
[2021-04-01] Scan GraphQL org for outdated (Facebook) copyright notices

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#662]
> Lee: is anyone aware of outstanding issues here?
> Ivan: I can do a check. I will search for “Facebook” under the GraphQL org
> [ACTION - Ivan]: see if there's any outdated Facebook copyright notices in GraphQL org

- assignee(s): @IvanGoncharov 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-04-01.md#review-previous-meetings-action-items-5m-lee

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Remaining:

* [ ] Swapi
* [ ] GraphQL.org

Need to do final scan

**Comment by brianwarner** [comment]
I did a spot check and the copyright lines look alright to me. We generally don't require those to be changed and in fact, nobody else can/should change Facebook's copyright line other than an authorized person from the company. We generally recommend projects follow [Steve Winslow's writeup on the topic](https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/). The good news is, it can stay as it is and be totally fine. That said, if some enterprising person wanted to add an additional copyright line that says "Copyright GraphQL contributors" (note there's no year in there), it'll be evergreen and won't ever need to be revved. 

That said, we should have a look at the license files in these two repos. And by "we", I mean, "I"...

I can take this one, @IvanGoncharov. I'll reassign it to myself.

**Comment by leebyron** [comment]
Thanks for that link, fascinating read!

I scanned through our repos looking specifically at the LICENSE files and found some variation which I cleaned up to all use the same MIT copy and evergreen copyright notice.

I left individual files alone, as suggested
