### ISSUE TITLE
[2021-05-13] Query Level Nullability - open PR

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#694]
> ACTION [Alex Reilly, Liz Jakubowski, Mark Larah, Sanae Rosen, Stephen Spalding, Wei Xue, Young Min Kim] - we'll open up a PR. We've a partial implementation on GraphQL.js

- assignee(s): @twof 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-05-13.md#query-level-nullability-rfc-15m-alex-reilly-stephen-spalding
---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@twof is this complete? I recall seeing some issues created.

**Comment by twof** [comment]
@benjie hey thanks for checking in! We've been working on the implementation first, and then we'll be turning it into a fully fledged RFC. People can track progress on the implementation in [this GraphQL.js fork](https://github.com/aprilrd/graphql-js/pull/5) And comment on [the strawman issue](https://github.com/graphql/graphql-spec/issues/867)  for now until we have something comprehensive up.

**Comment by twof** [comment]
Spec changes will be happening in this branch: https://github.com/graphql/graphql-spec/pull/895

The PR is not yet ready for review, but I'll update here when it is.

**Comment by twof** [comment]
The [spec PR](https://github.com/graphql/graphql-spec/pull/895) is ready for review!

**Comment by twof** [comment]
[Human readable RFC is up for review](https://github.com/graphql/graphql-wg/pull/772)
