### ISSUE TITLE
Special WG session during GraphQL EU

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#72]
I originally added https://github.com/graphql/graphql-wg/blob/master/agendas/2018-07-13.md with the intent that this be a special session where as many people who can join in person in Berlin during GraphQL EU can do so. However the specific date of July 13th is only a starting suggestion.

I want to use this issue as a space for us to work out options for what day and time this session should occur so those planning travel can work around a concrete plan.

**Comment by leebyron** [comment]
For some context, the [conference itself](https://www.graphql-europe.org/) is on the 15th which is a Sunday, so my thought was that the 13th (Friday), 14th (Saturday), or 16th (Monday) would be strong candidates.

**Comment by OlegIlyenko** [comment]
@leebyron I think you looked that July. The conference takes place on **June** 15th, 2018. So it's Friday, not Sunday

**Comment by leebyron** [comment]
Oh gosh you’re totally right. Thank you for correcting me

**Comment by leebyron** [comment]
I might propose holding the session on *Thursday, June 14th*, the day before the conference - however I know the tradeoff is that some may be preparing for the conference. @schickling what do you think?

**Comment by schickling** [comment]
Thursday June 14th would work for me, Saturday June 16th would certainly also be an option. 👍

**Comment by leebyron** [comment]
I actually like the idea of having the session directly after the conference - the only drawback being that it is a weekend, which is a big request for those not attending.

**Comment by leebyron** [comment]
We'll be holding this session on Thursday, June 14th - ideally in the late afternoon or early evening. @schickling can you help us find a location for people to meet who will be in town?

**Comment by leebyron** [comment]
Tentatively: 3-5pm

**Comment by schickling** [comment]
We're happy to host up to 15 people in our office. Otherwise we'll find another space! 🏠

**Comment by leebyron** [comment]
Should be plenty! 🙌

**Comment by IvanGoncharov** [comment]
@schickling @leebyron Would be great if you add time & address to agenda:
https://github.com/graphql/graphql-wg/blob/master/agendas/2018-06-14.md
