### ISSUE TITLE
Technical Steering Committee 2022 Elections

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-wg#765]
The GraphQL technical project is governed by our [technical steering committee (TSC)](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md).

The TSC was initially seeded in Nov 2020 with ten individuals plus the exec director (myself) with terms randomly assigned to be 1 or 2 years. Starting this year and going forward, we will hold elections for five seats per year with each elected member to serve a 2 year term.

### TSC election process overview:

Please read the complete [rules for this elections process](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#becoming-a-tsc-voting-member). However here is a brief overview:

1. Five TSC members end their terms on Dec 31st.
2. Between now and the end of the year we will nominate and elect five members for these seats.
3. Existing TSC members may (but are not required to) nominate themselves for an additional term.
4. The TSC members not up for election (remaining 5 plus myself) vote on nominees using the [Condorcet method](https://en.wikipedia.org/wiki/Condorcet_method).

### Upcoming dates:

|                  |       |
|  --------- | --- |
| **Nov 1** | Nominations open. If interested, please submit your name with [this form](https://tsc-nomination.graphql.org/).
| **Nov 29** | Nominations close.
| **Dec 1** | Voting by remaining TSC to begin.
| **Dec 27** | Voting ends and new TSC members announced (or earlier).
| **Dec 31** | Prior TSC members' term ends.
| **Jan 1, 2022** | New TSC members' two-year term begins. (Note: The next TSC/WG meeting to be held Jan 6th, 2022)
| **Dec 31, 2023** | New TSC members' two-year term ends.

### Expiring TSC member terms:

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Benjie Gillam](https://github.com/benjie)         | Graphile              | Nov 1, 2020 | Dec 31, 2021 |
| [Brielle Harrison](https://github.com/nyteshade)   | PayPal                | Nov 1, 2020 | Dec 31, 2021 |
| [Ivan Goncharov](https://github.com/IvanGoncharov) | Apollo                | Nov 1, 2020 | Dec 31, 2021 |
| [Matt Mahoney](https://github.com/mjmahone)        | Facebook              | Nov 1, 2020 | Dec 31, 2021 |
| [James Baxley](https://github.com/jbaxleyiii)      | Apollo GraphQL        | Nov 1, 2020 | Dec 31, 2021 |

### Members voting in this election:

| Name                                               | Affiliation           | Term begins | Term ends    |
| -------------------------------------------------- | --------------------- | ----------- | ------------ |
| [Lee Byron (chair)](https://github.com/leebyron)   | GraphQL Specification | N/A         | N/A          |
| [Andi Marek](https://github.com/andimarek)         | GraphQL Java          | Nov 1, 2020 | Dec 31, 2022 |
| [Dan Schafer](https://github.com/dschafer)         | Facebook              | Nov 1, 2020 | Dec 31, 2022 |
| [Nick Schrock](https://github.com/schrockn)        | Elementl              | Nov 1, 2020 | Dec 31, 2022 |
| [Rob Zhu](https://github.com/robzhu)               | AWS                   | Nov 1, 2020 | Dec 31, 2022 |
| [Sasha Solomon](https://github.com/sachee)         | Twitter               | Nov 1, 2020 | Dec 31, 2022 |

### TSC responsibilities overview:

Please read the complete [TSC scope](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#scope). However here is a brief overview of expectations:

* At a minimum, TSC members are responsible for guiding the GraphQL project via voting on approving proposals and spec releases.
* TSC members are encouraged to participate in working group meetings and help maintain technical progress, process and procedure.
* TSC members are administrators of Github and other technical spaces, and may be asked to help resolve problems.
* TSC members serve for two years, but may abandon their seat early via special election.

_Note: Working group meetings remain open to all who wish to join and contribute. The RFC process by which GraphQL evolves uses a consensus model, and TSC rarely intervene with this model. Our goal remains to maintain open contribution._

### Important links:

* [Self-nomination form](https://tsc-nomination.graphql.org/)
* [TSC information and rules](https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md)
* [GraphQL technical charter](https://github.com/graphql/foundation/blob/master/GraphQL%20Specification%20Membership%20Agreement%20February%202019.pdf)

I'm happy to answer any questions within this issue!

**Comment by IvanGoncharov** [comment]
@leebyron Thanks, Lee 👍 
Small clarification, I now work in Apollo (since Aug 2021) and I'm also sent PR to update the current TSC document: #767

**Comment by benjie** [comment]
Since nominations close tomorrow I've marked this ready for review. I've also filed it under Nov's WG for consistency with other action items.

**Comment by leebyron** [comment]
**Here are the results of the TSC election. The five winners (in alphabetical order) are:**

- Benjie Gillam
- Ivan Goncharov
- Marc-Andre Giroux
- Matt Mahoney
- Michael Staib

**Comment by leebyron** [comment]
A great thanks to past and present TSC members, and for everyone who self-nominated. We got quite a lot more nominations than I expected, which is *fantastic*.

I'd like to remind everyone who nominated that the TSC is a vote-holding position and carries accountability, but not the only set who take action and contribute to the core of the GraphQL project. I'm grateful for the energy you all provide to the project and community and hope that you continue to contribute

**Comment by leebyron** [comment]
- [x] Updated TSC charter
- [x] Updated Github `@graphql/tsc` team
