### ISSUE TITLE
[2021-06-03] Everyone: review the schema coordinates PR and implementation

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#788]
> Lee: review the PR to see if it is doing everything we want it to; then we can find out if there's any resistance to promoting it to Approved.
> [ACTION - everyone]: review the Schema Coordinates PR and implementation

- assignee(s): Everyone (champion: @magicmark)
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-06-03.md#schema-coordinates-update-5m-lee-mark

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@magicmark Please reply to this thread so I can assign you. Just a :wave: will do :+1:

**Comment by magicmark** [comment]
👋

**Comment by benjie** [comment]
As [agreed at the October 2023 WG](https://github.com/graphql/graphql-wg/blob/main/notes/2023/2023-10.md#review-previous-meetings-action-items-5m-lee); action items that have been inactive for more than 6 months can be closed. If you feel this issue is still requires more input, please comment below.
