### ISSUE TITLE
[2021-06-03] Fix visibility of new implementers team

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#789]
During the meeting some people could not see the new @graphql/implementers team.

I have a vague feeling you already fixed this @leebyron but the notes don't seem to confirm this.

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-06-03.md#full-unicode-support-5m-lee-andi

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by spawnia** [comment]
I am in it and got the notification 👋

**Comment by leebyron** [comment]
The visibility is "visible" but GitHub seems to have inherent limitations around teams:

https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams#:~:text=Visible%20teams%20can%20be%20viewed%20and%20%40mentioned%20by%20every%20organization%20member.

If you're a member of the GraphQL GitHub org then you can see these teams, but of course many community contributors are not. I do not know how to change this, but I suspect this is the root issue for why some couldn't see it
