### ISSUE TITLE
[2021-09-02] Raise GraphQL.js PR relating to relaxing field selection merging rules and speak to client developers

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#796]
Context: relax rule on Field Selection Merging to allow merging covariant fields Spec PR (15m, Ivan)

> Lee: I'd be dubious of completely removing it, whereas your proposed change here is sharp and smart and specifically narrows in on nullability being a different class of response shape definition. What's the range of removing the constraint - what does it involve now? Doing one doesn't prevent us from doing the other later.
> Ivan: for next time I'll prepare a GraphQL.js PR and speak to people working on clients - it's easier for me to do this now because Apollo have Android and iOS clients.

- assignee(s): @IvanGoncharov 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-09-02.md#relax-rule-on-field-selection-merging-to-allow-merging-covariant-fields-spec-pr-15m-ivan

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Note 11/2022 - still open, this is still worth investigating as it may help resolve complication and performance issues - this will help lead to a decision.

**Comment by benjie** [comment]
As [agreed at the October 2023 WG](https://github.com/graphql/graphql-wg/blob/main/notes/2023/2023-10.md#review-previous-meetings-action-items-5m-lee); action items that have been inactive for more than 6 months can be closed. If you feel this issue is still requires more input, please comment below. I don't recall it being raised this year; hopefully someone will champion it in future.
