### ISSUE TITLE
[2021-11-04] Client Controlled Nullability - add to list of unanswered questions - null vs error boundary?

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#798]
> Benjie: I agree that (!) and (?) need to be solved at the same time. Initially (?) made me uncomfortable, and now I understand better why. It could cause issues with your data model to come up that wouldn’t otherwise come up. If the underlying thing would have thrown an error anyway, it probably should still throw an error. These are slightly different behaviors.
> Lee: hesitant to have two different things - server-defined vs client-defined error. To take this to first principles - how will people want to use this?
> ACTION - add to our list of unanswered questions - it's not necessarily null, more an error boundary?

- assignee(s): @twof 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2021-11-04.md#progress-update-on-client-controlled-nullability-10m-alex-reilly

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@twof Please reply to this so I can assign you. A :wave:  will do :+1:

**Comment by twof** [comment]
👋

**Comment by twof** [comment]
This has been completed: https://docs.google.com/document/d/10MmZbzfPtk8GoAeSVm_m9ng8Aj10LBXVIQwkpjti6CQ/edit#heading=h.g7wzponnqnef
