### ISSUE TITLE
@DeferStream RFC - typo

### ISSUE THREAD

**Issue by rivantsov** [graphql/graphql-wg#858]
Not sure where to put this, but in DeferStream.md, looks like a typo in an example here: 
https://github.com/graphql/graphql-wg/blob/main/rfcs/DeferStream.md#example-query-with-defer-and-stream

the response payload 1 is listed as: 
```json
// payload 1
{
    data: {id: 1},
    hasNext: true
}
```

shouldn't it be: 

```json
// payload 1
{
    data:  { viewer:   {id: 1} },
    hasNext: true
}
```

**Comment by benjie** [comment]
@rivantsov You can send a PR to that file direct.

@robrichard I think @rivantsov is right, this seems to be a typo. Also typographical quotes have somehow crept into the code examples.

**Comment by robrichard** [comment]
@benjie I opened a PR to replace this example entirely with something I think is a bit clearer: https://github.com/graphql/graphql-wg/pull/863/files
