### ISSUE TITLE
Agenda: Define process for the changes to the specification

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-wg#9]
At the moment it's very hard to track which features will be included in the next release. 

For example, the absolute majority of the community thinks that IDL is already a part of the spec since it is implemented in all major libraries. However, it's still not merged into a spec and there is no clear indication of this PR status.

I propose to define a pipeline for all the major changes with stages marked as labels applied to PRs. I suggest using [TC39 process document](https://tc39.github.io/process-document/) as the base and adapt it to the specifics of GraphQL (reference implementation, WG, etc.).

It will give the community a sense of understanding on what's happening with GraphQL and allow library authors to do an educated decision on what experimental features they should support.

As for the editorial changes like grammar, examples, clarifications, etc. I propose to add separate simplified pipeline.

Should we discuss this at the next meeting?

**Comment by wincent** [comment]
Sounds like an eminently reasonable thing to discuss. Feel free to go ahead and add it to the agenda.

**Comment by IvanGoncharov** [comment]
@wincent Done
