### ISSUE TITLE
HTTP status code for partial responses 

### ISSUE THREAD

**Issue by saerdnaer** [graphql/graphql-wg#916]
Any thoughts on defining a dedicated HTTP Status code like 206 or 207 for partial successful responses, instead of only returning status 200 with an error array? 

- assignee(s): 
- source: 

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by n1ru4l** [comment]
I think this might be better of over on https://github.com/graphql/graphql-over-http

**Comment by saerdnaer** [comment]
Moved to https://github.com/graphql/graphql-over-http/issues/172
