### ISSUE TITLE
[2022-04-07] Unions implementing interfaces - exploration

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#953]
> - Lee: next actions:
>   - Better understand impact on execution. Does it change the way local selection sets work without needing fragment?
>   - Look for precedent from other languages
>   - Confusion of union implementing something (it being a constraint rather than union itself implementing) - perhaps it needs a different keyword - “contains”? I don’t know.

- assignee(s): @yaacovCR 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-04-07.md#discuss-proposal-to-allow-unions-to-declare-implementation-of-interfaces-15m-yaacov

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by yaacovCR** [comment]
-- No direct impact on execution, all execution changes are subsumed within schema.isSubType.

-- optional whether you could select interface fields directly on the Union

-- constraint can be alternatively be defined as an intersection on the Union, variation raised as separate PR... or just use a different keyword... or just use implements, my preference if we don't use intersection or other separate type

--
