### ISSUE TITLE
[2022-05-05] Final editorial review of "deprecation of input values"

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#971]
> Moved to S3: Accepted. I will do a final editorial review and merge into the draft. Great work everyone!

- assignee(s): @leebyron 
- source: https://github.com/graphql/graphql-spec/pull/805#issuecomment-1029319320 (raised here: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-05-05.md#review-previous-meetings-action-items-5m-lee)

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Applied editorial changed and merged
