### ISSUE TITLE
[2022-05-05] CCN - discussion thread on naming

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#974]
> Lee: to generalize, we should make sure we have the appropriate names/ways to describe these features. The names that make sense for one semantic might not make sense for another. But I do agree, the name we land on must make sense. I've been thinking ? is an "error boundary". ! is an assertion; other languages have similar syntax, but all use different names, e.g. Swift uses "unwrap".
> Roman: let's at least continue the discussion
> ACTION - Alex: open a discussion thread on naming.

:new: Timestamped video link: https://www.youtube.com/watch?v=Dlr65pNpJig&list=PLP1igyLx8foH30_sDnEZnxV_8pYW3SDtb&t=5568s

- assignee(s): @twof 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-05-05.md#ccn-status-update-and-rollout-plans-10m-alex-reilly

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
Thread was opened here: https://github.com/graphql/graphql-wg/discussions/965

(@twof Please reply so I can assign you, even though this is complete.)

**Comment by twof** [comment]
👋

**Comment by twof** [comment]
https://github.com/graphql/graphql-wg/discussions/965
