### ISSUE TITLE
[2022-05-05] CCN - AST node names

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#975]
> Ivan: Alex has done a great job, what's concerning me is naming. Even though it's experimental, if we rename it, it will be a breaking change. I'd rather we did the discussion up front before we commit to an API. Separate thread for naming makes sense. Need generic name for entire syntax for ?, ! and []. In AST we have one union type for these three types of nodes - so we need 4 names, and ideally decide those before we merge.
> Lee: I don't want perfection to be the enemy of the good, especially when we're iterating - we could spend a month picking the right name, and then change behavior based on feedback and now the name doesn't make sense any more.
> Michael: there's similar names in other languages, we should look at their syntax trees.
> ACTION: look through some naming conventions.

Related to #974, but I think it's separate?

:new: Timestamped video link: https://youtu.be/Dlr65pNpJig?list=PLP1igyLx8foH30_sDnEZnxV_8pYW3SDtb&t=6415

- assignee(s): @twof 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-05-05.md#ccn-status-update-and-rollout-plans-10m-alex-reilly

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by twof** [comment]
👋

**Comment by twof** [comment]
@benjie I also just want to say how much I appreciate that you pulled the entire exchange into text. I know how time consuming this sort of thing is, so seriously, thank you.

**Comment by twof** [comment]
Discussion thread: https://github.com/graphql/graphql-wg/discussions/994
