### ISSUE TITLE
[2022-05-05] Stream/defer - ensure spec wording is accurate relating to index format

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#976]
> Rob: so in summary, are we leaning towards option A but updating the language to "indicates starting position, overwrites length of array"
> ACTION - Rob: ensure the spec wording is accurate.

:new: Timestamped video link: https://youtu.be/Dlr65pNpJig?list=PLP1igyLx8foH30_sDnEZnxV_8pYW3SDtb&t=8921

- assignee(s): @robrichard 
- source: https://github.com/graphql/graphql-wg/blob/main/notes/2022/2022-05-05.md#deferstream-stream-payload-index-format-10m-rob

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by leebyron** [comment]
Spec PR is behind, open questions - but on the docket for July
