### ISSUE TITLE
Is 2 hours once a month long enough?

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-wg#988]
In the March WG last year, whilst trying to make the meetings easier to attend, we reduced their duration from 3 hours to 2 hours:

https://github.com/graphql/graphql-wg/blob/389d6c4eef16a949fae6daa4f88973a85f36e20f/notes/2021-03-04.md#alternate-wg-meeting-times-15m-andi

> Lee: maybe we can hold the meetings more frequently and have them be shorter. I've reduced the length of the next meeting to 2 hours. Having a shorter meeting might keep us more on point. We could do one every 3 weeks or two a month.

It feels like we've been pushing up against time for a few meetings now and have had to cut a few topics/discussions short. Thursday's WG also looks pretty full, and with our historical underestimation of how long each topic needs we may be quite tight on time.

I'm not proposing we change anything right now, but I think this is something worth keeping an eye on and thinking about - it could be just a particularly busy season, but if it continues we may want to increase meeting cadence or duration. Alternatively, we might introduce a policy of encouraging (not mandating) late additions to the agenda to be added to the next WG meeting instead if the current one is looking full. It would be nice if more meetings finished a few minutes ahead of schedule rather than pushing it to the line!

Let me know your thoughts :point_down:

**Comment by rivantsov** [comment]
I would vote for an extra meeting in between, contingent on agenda. It can be canceled if number of topics is low enough (<=3) to be pushed to the next 'regular' meeting

**Comment by rivantsov** [comment]
another suggestion - to establish a regular 'overflow' meeting, 1 week from regular meeting, contingent - might be canceled, to take on items that were beyond 2 hour time; it can use the same agenda, we just continue the meeting, where we stopped
Another suggestion - do 5 minutes coffee/bathroom breaks after every hour, these might not be in agenda, just as soon as we reach 1 hr

**Comment by leebyron** [comment]
Closing this one, now that we've put in place the two secondary meetings!
